const ADD_CONNECTION = 'ADD_CONNECTION';
const LOAD_CONNECTIONS = 'LOAD_CONNECTIONS';
const SET_CONNECTION_COLOR = 'SET_CONNECTION_COLOR';
const SELECT_CONNECTION = 'SELECT_CONNECTION';
const SET_DEVICE_COLOR = 'SET_DEVICE_COLOR';
const SELECT_DEVICE = 'SELECT_DEVICE';

export {
  ADD_CONNECTION,
  LOAD_CONNECTIONS,
  SET_CONNECTION_COLOR,
  SELECT_CONNECTION,
  SET_DEVICE_COLOR,
  SELECT_DEVICE
};
